[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[build.environment]
  NODE_VERSION = "12.14.1"
  YARN_VERSION = "1.21.1"
  YARN_FLAGS = "--pure-lockfile"
